(defun tea-encrypt (data key)
  (let ((v0 (first data))
        (v1 (second data))
        (sum 0)
        (delta #x9e3779b9)
        (k0 (first key))
        (k1 (second key))
        (k2 (third key))
        (k3 (fourth key)))
    (dotimes (i 32)
      (setq sum (+ sum delta))
      (setq v0 (+ (logxor v1 (ash (logxor v0 (lsh sum -4)) -1)) k0))
      (setq v1 (+ (logxor v0 (ash (logxor v1 (lsh sum -4)) -1)) k1))
      (setq v0 (+ (logxor v1 (ash (logxor v0 (lsh sum -4)) -1)) k2))
      (setq v1 (+ (logxor v0 (ash (logxor v1 (lsh sum -4)) -1)) k3)))
    (list v0 v1)))

(defun tea-decrypt (data key)
  (let ((v0 (first data))
        (v1 (second data))
        (sum #xC6EF3720)
        (delta #x9e3779b9)
        (k0 (first key))
        (k1 (second key))
        (k2 (third key))
        (k3 (fourth key)))
    (dotimes (i 32)
      (setq v1 (- v1 k3))
      (setq v0 (- v0 (logxor (ash v1 -1) (logxor v1 (lsh sum -4)))))
      (setq v1 (- v1 k2))
      (setq v0 (- v0 (logxor (ash v1 -1) (logxor v1 (lsh sum -4)))))
      (setq v1 (- v1 k1))
      (setq v0 (- v0 (logxor (ash v1 -1) (logxor v1 (lsh sum -4)))))
      (setq v1 (- v1 k0))
      (setq sum (- sum delta)))
    (list v0 v1)))
